
image: node:15.12.0

pipelines:
  branches:
    master:
        - step:
            name: Kymira EDICT App
            caches:
                - node
            script:
                - rm -rf package-lock.json
                - rm -rf node_modules
                - npm install
        - step:
            name: Create artifact
            script: 
                - git archive --format=tar.gz master -o application.tar.gz 
            artifacts: 
                - application.tar.gz
        - step:
            name: Deploy to heroku
            deployment: staging
            caches:
                - node
            script:
                - pipe: atlassian/heroku-deploy:1.2.1
                  variables:
                      HEROKU_API_KEY: $HEROKU_API_KEY
                      HEROKU_APP_NAME: $HEROKU_APP_NAME
                      ZIP_FILE: "application.tar.gz"
                      WAIT: 'true'